### ISSUE TITLE
In nose_mouth_30.dat.bz2 numbers representing nose and mouth are not correct.

### ISSUE THREAD

**Issue by lucky630** [Luca96/dlib-minified-models#1]
In nose_mouth_30.dat.bz2 numbers representing nose and mouth are not in sync with the image shown.  Because of that not able to extract only mouth coordinates from landmarks

**Comment by Luca96** [comment]
Hi @lucky630,
I've already spot the error.. I just need some time to generate the new models and upload everything.

**Comment by nyck33** [comment]
@Luca96 , @lucky630 

Also just wondering if it's possible to extract an eye-eyebrow-nose combination.

**Comment by lucky630** [comment]
I just got the points which represent the mouth.if someone is using this model can get the mouth coordinates by using points.
[28,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21].
I also tested this model accuracy is quite similar to the 68 - landmark points dlib model.
Thanks @Luca96 for providing this model

**Comment by Luca96** [comment]
Thanks @lucky630.
Actually, I'm re-training the models so that the coordinates of the landmarks will be same, like in the figure (the ones in the repo).

In addition, I will provide an example training script.
Meanwhile, you can check this [article](https://medium.com/datadriveninvestor/training-alternative-dlib-shape-predictor-models-using-python-d1d8f8bd9f5c) for more insight about how to create models with a custom set of landmarks.

**Comment by Luca96** [comment]
I've updated the models Commit https://github.com/Luca96/dlib-minified-models/commit/ba43cc2d6c26625cabdb9bc30abb651418986169  . Everything should be ok, now.

**Comment by lucky630** [comment]
Thanks @Luca96.
