### ISSUE TITLE
work support

### ISSUE THREAD

**Issue by picli3** [Luca96/dlib-minified-models#2]
hi Luca, I would like to know if you could make me a budget for a more accurate trained model of mouth and eyes. You can write to my email.

maykol.rey@services.mss.pe

**Comment by picli3** [comment]
![MyFace](https://i.imgur.com/J4UzE23.png)

**Comment by Luca96** [comment]
Hi, you can try training the model by following [this script](https://github.com/Luca96/dlib-minified-models/blob/master/face_landmarks/training_script.py).

I don't know your application requirements and constraints, but you can use the following **training options**:
```python
options = dlib.shape_predictor_training_options()
options.tree_depth = 4
options.nu = 0.1
options.cascade_depth = 15
options.feature_pool_size = 1000
options.num_test_splits = 300
```
With which you should achieve the best accuracy, but at the cost of a slower inference and a bigger model.

I've seen the screenshot you post. Maybe the problem is about the face location. How do you get the face bounding box? 
The trained models, that I provide (like the Dlib's original one), assume that the face is located by the Dlib **HOG face detector**. 

Hope it helps,
Regards.

**Comment by picli3** [comment]
hello Luca, thanks for your answer.

the face detection I'm doing with haar cascade. for now I have little time to do a training and try because I have more activities in the company.

I was wondering if you have a more accurate model, the hardware is a Jetson TX2.

**Comment by Luca96** [comment]
What set of landmarks should be located by the model? 
Only the eyes (points from 36 to 47) and mouth (points from 48 to 67) landmarks?

**Comment by picli3** [comment]
eyes from 36 to 47 and mouth from 48 to 59 and point 30 for the tip of the nose.

**Comment by Luca96** [comment]
I've trained [this model](https://github.com/Luca96/dlib-minified-models/blob/master/face_landmarks/custom%20models/eyes_mouth_nose_tip.dat.bz2) with the landmarks you need, and with a more accurate set of parameters. 
Let me know how it works.

**Comment by picli3** [comment]
thank you I await your answer, thank you really.
